# .github/workflows/actions.yml
# 이름 짓기
name: "Gitnub Actions 연습하기"
# 언제 이 작업을 실행할지 정의
# push: github에 push할 때마다 실행
on : push

jobs :
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository
        uses: actions/checkout@v5 

      - name: Node.js 설치
        uses: actions/setup-node@v6
        # 옵션: 노드 24 버전을 설치해
        with:
          node-version: 24
      - name: 의존성 설치
        run: npm ci

      - name: 테스트 실행
        run: npm run test

